export const getSEOConfig = ({
    title = "Sorriso Care - Affordable Dental Tourism",
    description = "Sorriso Care offers affordable dental tourism in the Balkans with high-quality dental care at low costs. Book your next dental trip today!",
    keywords = `
      veneers turkey, 
      cost for tooth implant, 
      Dental implants, 
      Teeth implants, 
      Tooth implants, 
      full mouth dental implants, 
      all on 4 dental implants, 
      teeth implants cost, 
      hair transplant turkey, 
      smile dentist, 
      rotten teeth, 
      cavities in teeth, 
      tooth decay, 
      Perfect smile, 
      Cosmetic dentistry, 
      Dental crown, 
      dental bridge, 
      Smile makeover, 
      Turkey teeth, 
      Montenegro, 
      fly to montenegro, 
      New Year, 
      Cavity, 
      bad teeth, 
      dental tourism, 
      affordable dental care, 
      affordable veneers, 
      dental treatment Balkans, 
      Sorriso Care, 
      Montenegro dental services, 
      Montenegro dentist, 
      Montenegro dental implants, 
      implanti dentali costo, 
      quanto costa un impianto dentale, 
      impianto dentale, 
      implantologia, 
      faccette dentali, 
      costi faccette dentali, 
      ponte dentale, 
      rifarsi i denti, 
      dentista vicino a me, 
      dentisti in Croazia, 
      dentista Croazia, 
      cure dentali Croazia, 
      cliniche dentali Croazia, 
      cliniche dentali Turchia, 
      cliniche dentali Albania, 
      all-on-4, 
      all-on-6, 
      all on 4 implants Balkans, 
      all on 6 Montenegro, 
      dental veneers Balkans, 
      cosmetic dentistry Montenegro, 
      smile makeover Montenegro, 
      dental bridges Balkans, 
      dental crowns Balkans, 
      teeth whitening Montenegro, 
      dental holiday Montenegro, 
      fly to Montenegro for dentistry, 
      affordable dental implants, 
      dental tourism Croatia, 
      tooth decay treatment Montenegro, 
      rotten teeth makeover, 
      teeth implants Albania, 
      teeth implants Turkey, 
      tooth extraction Montenegro, 
      cheap dental clinics, 
      Montenegro vacation dentistry, 
      dental travel packages, 
      dental packages Balkans, 
      best dental clinics Europe, 
      budget dental solutions, 
      cosmetic dental surgery Montenegro, 
      dentist for implants, 
      tooth replacement Balkans, 
      smile dentist Europe, 
      teeth tourism Balkans, 
      tooth surgery Montenegro, 
      dental implant tourism, 
      affordable dental crowns, 
      new smile, 
      full mouth reconstruction, 
      dental health Europe, 
      veneers cost Europe, 
      cheap veneers Europe, 
      dental veneers for bad teeth, 
      implants for tooth loss, 
      veneers Turkey reviews, 
      low-cost dental treatment, 
      dental implant procedure, 
      affordable smile design, 
      smile design,
      sorriso,
      sorriso bello, 
      sorriso perfetto,
      sorriso denti,
      affordable dental care,
      sorriso care, 
      dental tourism,
      dental vacation,
      dental holiday,
      dental travel,
      dental trip,
      dental journey,
      dental destination,
      dental getaway,
      dental retreat,
      dental break,
      full-mouth reconstruction,
      full-mouth restoration,
      full-mouth rehabilitation,
      full-mouth makeover,
      full-mouth transformation,
      full-mouth rejuvenation,
      full-mouth reconditioning,
      teeth cleaning Montenegro, 
      affordable root canal Montenegro, 
      new year dental deals, 
      fly to Balkans for dental care
    `,
    url = "https://sorriso.care/",
    image = "https://sorriso.care/images/icons/icon.svg",
  }: {
    title?: string;
    description?: string;
    keywords?: string;
    url?: string;
    image?: string;
  }) => ({
    title,
    description,
    keywords,
    robots: "index, follow",
    canonical: url,
    viewport: "width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no",
    charSet: "UTF-8",
    xUACompatible: "IE=edge",
    themeColor: "#ffffff",
    applicationName: "Sorriso Care",
    openGraph: {
      title,
      description,
      url,
      siteName: "Sorriso Care",
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: "Sorriso Care Logo",
        },
      ],
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      site: "@sorriso_care",
      title,
      description,
      images: [image],
    },
    structuredData: {
      "@context": "https://schema.org",
      "@type": "Organization",
      name: "Sorriso Care",
      url,
      logo: image,
      sameAs: [
        "https://www.facebook.com/sorrisocare",
        "https://www.linkedin.com/company/sorriso-care",
        "https://www.instagram.com/sorriso_care/",
      ],
      contactPoint: {
        "@type": "ContactPoint",
        telephone: "+382 60 664 668",
        contactType: "Customer Service",
        areaServed: "Balkans",
        availableLanguage: ["English", "Montenegrin", "Italian"],
      },
      description,
      founder: {
        "@type": "Person",
        name: "Dr. Filip Šuković",
      },
      address: {
        "@type": "PostalAddress",
        addressLocality: "Podgorica",
        addressCountry: "Montenegro",
        postalCode: "81000",
        streetAddress: "bb Gavra Vukovića",
      },
    },
  });
  